kind: pipeline
name: development
type: vm

pool:
  use: ubuntu-aws

steps:
  - name: build & test
    image: gcc:13.1.0
    pull: true
    commands:
      - chmod u+x ./scripts/setup.sh ; ./scripts/setup.sh
      - chmod u+x ./scripts/venv.sh
      - . ./scripts/venv.sh
      - conan profile detect
      - chmod u+x ./scripts/build.sh ; ./scripts/build.sh
      - chmod u+x ./scripts/test.sh ; ./scripts/test.sh
